#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

requested_image_repository="${SCOUTOPS_IMAGE_REPOSITORY:-}"
requested_image_tag="${SCOUTOPS_IMAGE_TAG:-}"
if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi
SCOUTOPS_IMAGE_REPOSITORY="${requested_image_repository:-${SCOUTOPS_IMAGE_REPOSITORY:-}}"
SCOUTOPS_IMAGE_TAG="${requested_image_tag:-${SCOUTOPS_IMAGE_TAG:-}}"
export SCOUTOPS_IMAGE_REPOSITORY SCOUTOPS_IMAGE_TAG

required=(SCOUTOPS_IMAGE_REPOSITORY SCOUTOPS_IMAGE_TAG DB_NAME DB_USER DB_PASSWORD JWT_SECRET ADMIN_USERNAME ADMIN_PASSWORD METRICS_TOKEN TLS_CERT_DIR TLS_HOSTNAME)
for name in "${required[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    echo "$name must be configured in the environment or .env." >&2
    exit 1
  fi
done

if [[ ! "$SCOUTOPS_IMAGE_TAG" =~ ^[0-9]+-[0-9a-f]{12}$ ]]; then
  echo "Use the immutable <build-number>-<12-character-git-sha> image tag generated by Jenkins." >&2
  exit 1
fi

COMPOSE=(docker compose -f docker-compose.prod.yml)
PREVIOUS_TAG=""
container_id="$(docker ps -q --filter label=com.docker.compose.service=scoutops-app | head -n 1)"
if [[ -n "$container_id" ]]; then
  current_image="$(docker inspect --format '{{.Config.Image}}' "$container_id")"
  PREVIOUS_TAG="${current_image##*:}"
fi

echo "Pulling ScoutOps image $SCOUTOPS_IMAGE_REPOSITORY:$SCOUTOPS_IMAGE_TAG..."
"${COMPOSE[@]}" pull scoutops-app

echo "Starting the production stack..."
"${COMPOSE[@]}" up -d --remove-orphans

for attempt in $(seq 1 30); do
  if curl --resolve "$TLS_HOSTNAME:443:127.0.0.1" --fail --silent "https://$TLS_HOSTNAME/health" >/dev/null; then
    printf '%s\n' "$PREVIOUS_TAG" > .scoutops-previous-tag
    echo "Deployment health check passed."
    exit 0
  fi
  sleep 2
done

echo "New deployment did not become healthy within 60 seconds." >&2
if [[ -n "$PREVIOUS_TAG" && "$PREVIOUS_TAG" != "$SCOUTOPS_IMAGE_TAG" ]]; then
  echo "Restoring previous image $PREVIOUS_TAG..." >&2
  SCOUTOPS_IMAGE_TAG="$PREVIOUS_TAG" "${COMPOSE[@]}" up -d --no-deps scoutops-app
fi
exit 1
